#!/usr/bin/env python3
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any

try:
    import tomllib  # py311+
except ModuleNotFoundError:  # py310
    import tomli as tomllib

from common_utils import extract_share_id, make_zip_dir, read_urls_file_with_passwords
from multi_download import detect_provider, run_cloud_one, run_fz_one, run_nyfy_one, run_tz_one

DEFAULT_CONFIG_FILE = "dicom_download.toml"
DEFAULT_URLS_FILE = "urls.txt"
DEFAULTS: dict[str, Any] = {
    "url": None,
    "urls_file": None,
    "provider": "auto",
    "mode": "all",
    "headless": False,
    "skip_hd": False,
    "hd_timeout_ms": 10000,
    "max_rounds": 3,
    "step_wait_ms": 50,
    "quiet_checks": 6,
    "quiet_step_ms": 800,
    "max_inflight": 6,
    "overwrite": False,
    "cloud_password": None,
    "cloud_raw": False,
    "cloud_keep_temp": False,
    "nyfy_concurrency": 2,
    "nyfy_download_retries": 4,
    "nyfy_http_timeout_ms": 60000,
    "nyfy_retry_backoff_ms": 250,
    "nyfy_backfill_rounds": 5,
    "nyfy_verify": False,
    "out_parent": "./downloads",
    "no_zip": False,
}
SAVED_CONFIG_KEYS = [key for key in DEFAULTS if key not in {"url", "urls_file", "cloud_password"}]
MENU_CONFIG_KEYS = ["provider", "mode", "headless", "max_rounds", "step_wait_ms", "out_parent", "skip_hd", "no_zip", "overwrite"]


# ================== 配置与序列化 ==================


def load_toml_config(config_path: str | None) -> dict[str, Any]:
    if not config_path:
        return {}

    path = Path(config_path)
    if not path.exists():
        return {}

    with path.open("rb") as f:
        data = tomllib.load(f)
    return data if isinstance(data, dict) else {}


def pick_config_defaults(config: dict[str, Any]) -> dict[str, Any]:
    defaults = dict(DEFAULTS)
    for key in defaults:
        if key in config and config[key] is not None:
            defaults[key] = config[key]
    return defaults


def _toml_escape(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def dump_toml_config(data: dict[str, Any]) -> str:
    lines: list[str] = ["# Auto-generated by main.py"]
    for key in SAVED_CONFIG_KEYS:
        value = data.get(key)
        if value is None:
            continue
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        elif isinstance(value, (int, float)):
            rendered = str(value)
        else:
            rendered = _toml_escape(str(value))
        lines.append(f"{key} = {rendered}")
    lines.append("")
    return "\n".join(lines)


def build_config_payload(args: argparse.Namespace) -> dict[str, Any]:
    payload: dict[str, Any] = {}
    for key in SAVED_CONFIG_KEYS:
        payload[key] = getattr(args, key, DEFAULTS.get(key))
    return payload


def write_config_file(path: str | Path, data: dict[str, Any]) -> Path:
    target = Path(path)
    if target.parent and str(target.parent) not in {"", "."}:
        target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(dump_toml_config(data), encoding="utf-8")
    return target


def ensure_starter_config_file(config_path: str, explicit_config: bool) -> bool:
    """Create a starter config on first run when using the default path."""
    if explicit_config:
        return False
    if config_path != DEFAULT_CONFIG_FILE:
        return False

    target = Path(config_path)
    if target.exists():
        return False

    write_config_file(target, dict(DEFAULTS))
    return True


def load_effective_state(config_path: str = DEFAULT_CONFIG_FILE) -> tuple[str, dict[str, Any], bool]:
    generated = ensure_starter_config_file(config_path, explicit_config=False)
    state = pick_config_defaults(load_toml_config(config_path))
    return config_path, state, generated


# ================== 终端交互 ==================


def prompt_text(label: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default not in {None, ""} else ""
    value = input(f"{label}{suffix}: ").strip()
    if value == "" and default is not None:
        return str(default)
    return value


def prompt_yes_no(label: str, default: bool = False) -> bool:
    suffix = "Y/n" if default else "y/N"
    value = input(f"{label} ({suffix}): ").strip().lower()
    if value == "":
        return default
    return value in {"y", "yes", "1", "true", "t"}


def prompt_int(label: str, default: int) -> int:
    while True:
        value = input(f"{label} [{default}]: ").strip()
        if value == "":
            return default
        try:
            return int(value)
        except ValueError:
            print("    请输入数字。")


def show_menu() -> None:
    print("\n=== DICOM 下载菜单 ===")
    print("1. 单 URL 下载（粘贴一个链接）")
    print("2. 本地 txt 批量下载（输入 txt 路径）")
    print(f"3. 默认 {DEFAULT_URLS_FILE} 下载（直接回车即可）")
    print("4. 查看配置")
    print("5. 修改并保存配置")
    print("6. 保存当前配置")
    print("7. 退出")


def show_config(config_path: str, state: dict[str, Any]) -> None:
    print(f"\n>>> 当前配置文件：{os.path.abspath(config_path)}")
    print(dump_toml_config(state))


def collect_menu_settings(state: dict[str, Any]) -> dict[str, Any]:
    updated = dict(state)
    print("\n--- 请确认下载参数（直接回车使用默认值）---")
    updated["provider"] = prompt_text("provider(auto/tz/fz/nyfy/cloud)", str(state.get("provider", "auto")))
    updated["mode"] = prompt_text("mode(diag/nondiag/all)", str(state.get("mode", "all")))
    updated["headless"] = prompt_yes_no("是否无界面运行", bool(state.get("headless", False)))
    updated["max_rounds"] = prompt_int("max_rounds", int(state.get("max_rounds", 3)))
    updated["step_wait_ms"] = prompt_int("step_wait_ms", int(state.get("step_wait_ms", 50)))
    updated["out_parent"] = prompt_text("输出目录", str(state.get("out_parent", "./downloads")))
    updated["skip_hd"] = prompt_yes_no("跳过高清切换", bool(state.get("skip_hd", False)))
    updated["no_zip"] = prompt_yes_no("不生成 zip", bool(state.get("no_zip", False)))
    updated["overwrite"] = prompt_yes_no("若目录已存在则覆盖", bool(state.get("overwrite", False)))
    return updated


def build_runtime_namespace(state: dict[str, Any], url: str | None = None, urls_file: str | None = None) -> argparse.Namespace:
    payload = dict(state)
    payload["url"] = url
    payload["urls_file"] = urls_file
    payload.setdefault("cloud_password", None)
    payload["config"] = DEFAULT_CONFIG_FILE
    payload["save_config"] = False
    payload["_explicit_config"] = False
    return argparse.Namespace(**payload)


# ================== 下载执行 ==================


def build_parser(defaults: dict[str, Any]) -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        description="DICOM 下载主入口：支持单 URL、本地 txt、默认 urls.txt，并可通过 TOML 配置默认参数",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument(
        "--config",
        default=DEFAULT_CONFIG_FILE,
        help="TOML 配置文件路径（默认 dicom_download.toml；不存在时会自动生成一个模板）",
    )
    ap.add_argument(
        "--save-config",
        action="store_true",
        help="把当前命令行生效参数保存为 TOML 后退出（不包含 URL、urls-file 和密码）",
    )

    group = ap.add_mutually_exclusive_group(required=False)
    group.add_argument("--url", default=defaults["url"], help="单个检查链接 URL")
    group.add_argument(
        "--urls-file",
        default=defaults["urls_file"],
        help="包含多个 URL 的本地文本文件（每行一个，支持 # 注释）",
    )

    ap.add_argument(
        "--provider",
        choices=["auto", "tz", "fz", "nyfy", "cloud"],
        default=defaults["provider"],
        help=(
            "手动指定 provider（默认 auto：按域名自动识别）。"
            "tz=天肿(zlyy.tjmucih.cn)，fz=复肿(ylyyx.shdc.org.cn)，nyfy=宁夏总医院(zhyl.nyfy.com.cn)"
        ),
    )
    ap.add_argument(
        "--mode",
        choices=["diag", "nondiag", "all"],
        default=defaults["mode"],
        help="下载模式（对 UI 抓取策略生效）",
    )
    ap.add_argument("--headless", action="store_true", default=defaults["headless"], help="无界面模式运行")
    ap.add_argument("--no-headless", dest="headless", action="store_false")

    ap.add_argument("--skip-hd", action="store_true", default=defaults["skip_hd"], help="跳过高清切换（复肿 fz 有效）")
    ap.add_argument("--hd-timeout-ms", type=int, default=defaults["hd_timeout_ms"], help="高清切换超时（毫秒）")
    ap.add_argument("--max-rounds", type=int, default=defaults["max_rounds"], help="逐帧播放轮数上限（复肿 fz）")
    ap.add_argument("--step-wait-ms", type=int, default=defaults["step_wait_ms"], help="逐帧间隔（毫秒）（复肿 fz）")
    ap.add_argument("--quiet-checks", type=int, default=defaults["quiet_checks"], help="静默观察次数（复肿 fz）")
    ap.add_argument("--quiet-step-ms", type=int, default=defaults["quiet_step_ms"], help="静默观察间隔（毫秒）（复肿 fz）")
    ap.add_argument("--max-inflight", type=int, default=defaults["max_inflight"], help="抓取/写盘最大并发（复肿 fz）")
    ap.add_argument("--overwrite", action="store_true", default=defaults["overwrite"], help="若输出目录存在则先删除（复肿 fz）")

    ap.add_argument(
        "--cloud-password",
        default=defaults["cloud_password"],
        help="cloud provider 密码（仅 *.medicalimagecloud.com 这类链接必需）",
    )
    ap.add_argument("--cloud-raw", action="store_true", default=defaults["cloud_raw"], help="cloud provider 下载 raw（上游 --raw；默认下载 JPEG2000 无损）")
    ap.add_argument("--cloud-keep-temp", action="store_true", default=defaults["cloud_keep_temp"], help="cloud provider 失败/调试时保留临时目录（打印路径）")

    ap.add_argument("--nyfy-concurrency", type=int, default=defaults["nyfy_concurrency"], help="宁夏总医院（nyfy）下载并发")
    ap.add_argument("--nyfy-download-retries", type=int, default=defaults["nyfy_download_retries"], help="宁夏总医院（nyfy）重试次数")
    ap.add_argument("--nyfy-http-timeout-ms", type=int, default=defaults["nyfy_http_timeout_ms"], help="宁夏总医院（nyfy）HTTP 超时")
    ap.add_argument("--nyfy-retry-backoff-ms", type=int, default=defaults["nyfy_retry_backoff_ms"], help="宁夏总医院（nyfy）重试退避（毫秒）")
    ap.add_argument("--nyfy-backfill-rounds", type=int, default=defaults["nyfy_backfill_rounds"], help="宁夏总医院（nyfy）回填轮数")
    ap.add_argument("--nyfy-verify", action="store_true", default=defaults["nyfy_verify"], help="宁夏总医院（nyfy）下载后校验 DICOM")
    ap.add_argument("--nyfy-no-verify", dest="nyfy_verify", action="store_false")

    ap.add_argument("--out-parent", default=defaults["out_parent"], help="输出父目录（每个 URL 会建一个 share_id 子目录）")
    ap.add_argument("--no-zip", action="store_true", default=defaults["no_zip"], help="不为每个 URL 生成 zip")
    return ap


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    if argv is None:
        argv = sys.argv[1:]

    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--config", default=DEFAULT_CONFIG_FILE)
    pre_args, _ = pre.parse_known_args(argv)
    explicit_config = any(token == "--config" or token.startswith("--config=") for token in argv)

    config = load_toml_config(pre_args.config)
    defaults = pick_config_defaults(config)
    parser = build_parser(defaults)
    args = parser.parse_args(argv)
    args.config = pre_args.config
    args._explicit_config = explicit_config  # type: ignore[attr-defined]
    return args


def resolve_urls_with_passwords(args: argparse.Namespace) -> list[tuple[str, str | None]]:
    if args.url:
        return [(args.url, None)]

    urls_file = args.urls_file or DEFAULT_URLS_FILE
    path = Path(urls_file)
    if not path.is_absolute():
        path = Path.cwd() / path

    if not path.exists():
        raise FileNotFoundError(
            f"未找到输入文件：{path}\n"
            "请使用 --url 指定单个链接，或使用 --urls-file 指定 txt 文件，"
            f"也可以在当前目录放置默认的 {DEFAULT_URLS_FILE}。"
        )

    return read_urls_file_with_passwords(str(path))


async def run_one(url: str, password: str | None, out_dir: str, args: argparse.Namespace) -> None:
    prov = args.provider if args.provider != "auto" else detect_provider(url)

    if prov == "tz":
        await run_tz_one(url, out_dir, args.mode, args.headless)
    elif prov == "fz":
        await run_fz_one(url, out_dir, args.mode, args.headless, args, password)
    elif prov == "nyfy":
        await run_nyfy_one(url, out_dir, args.headless, args.out_parent, args)
    elif prov == "cloud":
        run_cloud_one(url, out_dir, args)
    else:
        await run_fz_one(url, out_dir, args.mode, args.headless, args, password)


async def run_download(args: argparse.Namespace, urls_with_password: list[tuple[str, str | None]] | None = None) -> None:
    if args.save_config:
        write_config_file(args.config, build_config_payload(args))
        print(f">>> 已保存配置：{os.path.abspath(args.config)}")
        return

    generated = ensure_starter_config_file(args.config, getattr(args, "_explicit_config", False))
    if generated:
        print(f">>> 已生成默认配置模板：{os.path.abspath(args.config)}")

    if urls_with_password is None:
        urls_with_password = resolve_urls_with_passwords(args)

    out_parent = os.path.abspath(args.out_parent)
    os.makedirs(out_parent, exist_ok=True)

    print("\n>>> 启动参数：")
    print(f"    config      : {args.config}")
    print(f"    URL数量     : {len(urls_with_password)}")
    print(f"    out_parent  : {out_parent}")
    print(f"    provider    : {args.provider}")
    print(f"    mode        : {args.mode}")
    print(f"    headless    : {args.headless}")
    print(f"    max_rounds  : {args.max_rounds}")
    print(f"    step_wait   : {args.step_wait_ms}ms\n")

    for i, (url, password) in enumerate(urls_with_password, start=1):
        share_id = extract_share_id(url)
        out_dir = os.path.join(out_parent, share_id)
        os.makedirs(out_dir, exist_ok=True)

        prov = args.provider if args.provider != "auto" else detect_provider(url)
        print("=" * 80)
        print(f"### [{i}/{len(urls_with_password)}] provider={prov}")
        print(f"URL      : {url}")
        if password:
            print(f"安全码   : {'*' * len(password)}")
        print(f"输出目录 : {out_dir}")
        print("=" * 80)

        try:
            await run_one(url, password, out_dir, args)
        except Exception as e:
            print(f">>> ❌ 失败：{url}")
            print(f">>> 错误：{e}")
            continue

        if not args.no_zip:
            zip_path = os.path.join(out_parent, f"{share_id}.zip")
            make_zip_dir(out_dir, zip_path)
            print(f">>> zip 已生成：{os.path.abspath(zip_path)}")

    print("\n>>> 全部任务结束")


async def main_async(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    await run_download(args)


# ================== 菜单模式 ==================


def select_menu_action() -> str:
    while True:
        show_menu()
        choice = input("请选择功能 [7]: ").strip() or "7"
        if choice in {"1", "2", "3", "4", "5", "6", "7"}:
            return choice
        print("    请输入 1-7。")


def interactive_main() -> None:
    config_path, state, generated = load_effective_state(DEFAULT_CONFIG_FILE)
    if generated:
        print(f">>> 已生成默认配置模板：{os.path.abspath(config_path)}")

    choice = select_menu_action()

    if choice == "1":
        url = prompt_text("请输入单个检查链接 URL")
        password = prompt_text("安全码（可选，直接回车跳过）", "") or None
        updated = collect_menu_settings(state)
        args = build_runtime_namespace(updated, url=url)
        asyncio.run(run_download(args, urls_with_password=[(url, password)]))
        return

    if choice == "2":
        path = prompt_text("请输入 txt 文件路径", DEFAULT_URLS_FILE)
        updated = collect_menu_settings(state)
        args = build_runtime_namespace(updated, urls_file=path)
        asyncio.run(run_download(args))
        return

    if choice == "3":
        updated = collect_menu_settings(state)
        args = build_runtime_namespace(updated, urls_file=DEFAULT_URLS_FILE)
        asyncio.run(run_download(args))
        return

    if choice == "4":
        show_config(config_path, state)
        return

    if choice == "5":
        updated = collect_menu_settings(state)
        write_config_file(config_path, updated)
        print(f">>> 已保存配置：{os.path.abspath(config_path)}")
        return

    if choice == "6":
        write_config_file(config_path, state)
        print(f">>> 已保存配置：{os.path.abspath(config_path)}")
        return

    print(">>> 已退出")


# ================== 命令行入口 ==================


def main() -> None:
    if len(sys.argv) > 1:
        asyncio.run(main_async())
        return
    interactive_main()


if __name__ == "__main__":
    main()
